# Data Exploration

### Video Game Sales Dataset - Column Descriptions

| Column Name | Description |
|---|---|
| `Rank` | The ranking position of the video game based on global sales. Lower numbers indicate higher sales performance. |
| `Name` | The title or name of the video game. |
| `Platform` | The gaming platform or console on which the game was released, such as Wii, PS4, Xbox, or PC. |
| `Year` | The release year of the video game. Some rows may contain missing values if the release year is unknown. |
| `Genre` | The category or type of the game, such as Action, Sports, Racing, Role-Playing, or Shooter. |
| `Publisher` | The company responsible for publishing the video game. Some rows may contain missing values. |
| `NA_Sales` | Total sales of the game in North America, measured in millions of units. |
| `EU_Sales` | Total sales of the game in Europe, measured in millions of units. |
| `JP_Sales` | Total sales of the game in Japan, measured in millions of units. |
| `Other_Sales` | Total sales in other regions outside North America, Europe, and Japan, measured in millions of units. |
| `Global_Sales` | Total worldwide sales of the game, measured in millions of units. This is the sum of regional sales columns. |

### Dataset Summary

- **Number of Rows:** 16,598
- **Number of Columns:** 11
- **Dataset Topic:** Video game sales across different regions and platforms.

In [11]:
import numpy as np
import pandas as pd
import plotly.express as px

In [12]:
df = pd.read_csv('vgsales.csv')
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

### Check Data types

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  str
 2   Platform      16598 non-null  str
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  str
 5   Publisher     16540 non-null  str
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 1.4 MB

### Check Summary Statistics for Numerical columns

In [14]:
df.describe().round(2)

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.00,16327.00,16598.00,16598.00,16598.00,16598.00,16598.00
mean,8300.61,2006.41,0.26,0.15,0.08,0.05,0.54
std,4791.85,5.83,0.82,0.51,0.31,0.19,1.56
min,1.00,1980.00,0.00,0.00,0.00,0.00,0.01
25%,4151.25,2003.00,0.00,0.00,0.00,0.00,0.06
50%,8300.50,2007.00,0.08,0.02,0.00,0.01,0.17
75%,12449.75,2010.00,0.24,0.11,0.04,0.04,0.47
max,16600.00,2020.00,41.49,29.02,10.22,10.57,82.74

### Check Summary Statistics for Categorical columns

In [15]:
df.describe(include= ['object'])

C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_23244\2270142546.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include= ['object'])

                               Name Platform   Genre        Publisher
count                         16598    16598   16598            16540
unique                        11493       31      12              578
top     Need for Speed: Most Wanted       DS  Action  Electronic Arts
freq                             12     2163    3316             1351

### Check Duplicates

In [16]:
df.duplicated().sum()

np.int64(0)

### Check Missing Values

In [18]:
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

# Data Cleaning and Preprocessing

### In depth check for numerical columns

In [19]:
num_cols = df.select_dtypes(include= 'number').columns.drop('Rank')
num_cols

Index(['Year', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales',
       'Global_Sales'],
      dtype='str')

In [20]:
for col in num_cols:

    px.histogram(data_frame= df, x= col, title= col).show()
    px.box(data_frame= df, x= col, title= col).show()

In [21]:
df[df['NA_Sales'] == 0]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
214,215,Monster Hunter Freedom 3,PSP,2010.0,Role-Playing,Capcom,0.0,0.00,4.87,0.00,4.87
338,339,Friend Collection,DS,2009.0,Misc,Nintendo,0.0,0.00,3.67,0.00,3.67
383,384,Monster Hunter 4,3DS,2013.0,Role-Playing,Capcom,0.0,0.00,3.44,0.00,3.44
402,403,English Training: Have Fun Improving Your Skills!,DS,2006.0,Misc,Nintendo,0.0,0.99,2.32,0.02,3.33
426,427,Dragon Quest VI: Maboroshi no Daichi,SNES,1995.0,Role-Playing,Enix Corporation,0.0,0.00,3.19,0.00,3.19
...,...,...,...,...,...,...,...,...,...,...,...
16587,16590,Mezase!! Tsuri Master DS,DS,2009.0,Sports,Hudson Soft,0.0,0.00,0.01,0.00,0.01
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.0,0.00,0.01,0.00,0.01
16590,16593,Eiyuu Densetsu: Sora no Kiseki Material Collec...,PSP,2007.0,Role-Playing,Falcom Corporation,0.0,0.00,0.01,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.0,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.0,0.01,0.00,0.00,0.01

In [22]:
df[df['EU_Sales'] == 0]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
147,148,Final Fantasy XII,PS2,2006.0,Role-Playing,Square Enix,1.88,0.0,2.33,1.74,5.95
214,215,Monster Hunter Freedom 3,PSP,2010.0,Role-Playing,Capcom,0.00,0.0,4.87,0.00,4.87
265,266,Metal Gear Solid 3: Snake Eater,PS2,2004.0,Action,Konami Digital Entertainment,1.46,0.0,0.83,1.93,4.23
281,282,Half-Life,PC,1997.0,Shooter,Vivendi Games,4.03,0.0,0.09,0.00,4.12
312,313,Dragon Warrior III,NES,1988.0,Role-Playing,Enix Corporation,0.10,0.0,3.77,0.00,3.87
...,...,...,...,...,...,...,...,...,...,...,...
16592,16595,Plushees,DS,2008.0,Simulation,Destineer,0.01,0.0,0.00,0.00,0.01
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.0,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.0,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.0,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.0,0.00,0.00,0.01

In [23]:
df[df['JP_Sales'] == 0]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
60,61,Just Dance 3,Wii,2011.0,Misc,Ubisoft,6.05,3.15,0.0,1.07,10.26
83,84,The Sims 3,PC,2009.0,Simulation,Electronic Arts,0.98,6.42,0.0,0.71,8.11
89,90,Pac-Man,2600,1982.0,Puzzle,Atari,7.28,0.45,0.0,0.08,7.81
98,99,Call of Duty: World at War,X360,2008.0,Shooter,Activision,4.79,1.90,0.0,0.69,7.37
102,103,Just Dance,Wii,2009.0,Misc,Ubisoft,3.51,3.03,0.0,0.73,7.27
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.00,0.01

In [24]:
df[df['Other_Sales'] == 0]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
137,138,World of Warcraft,PC,2004.0,Role-Playing,Activision,0.07,6.21,0.00,0.0,6.28
214,215,Monster Hunter Freedom 3,PSP,2010.0,Role-Playing,Capcom,0.00,0.00,4.87,0.0,4.87
281,282,Half-Life,PC,1997.0,Shooter,Vivendi Games,4.03,0.00,0.09,0.0,4.12
288,289,World of Warcraft: The Burning Crusade,PC,2007.0,Role-Playing,Activision,2.57,1.52,0.00,0.0,4.09
312,313,Dragon Warrior III,NES,1988.0,Role-Playing,Enix Corporation,0.10,0.00,3.77,0.0,3.87
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.0,0.01

### In depth check for categorical columns

In [142]:
df.columns = df.columns.str.strip()
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales',
       'Platform_Family'],
      dtype='str')

In [144]:
cat_cols = df.select_dtypes(include= 'object').columns
cat_cols

C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_23244\3692946097.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include= 'object').columns

Index(['Name', 'Platform', 'Genre', 'Publisher', 'Platform_Family'], dtype='str')

In [145]:
for col in cat_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 100)

Name
11493
<StringArray>
[                                                 'Wii Sports',
                                           'Super Mario Bros.',
                                              'Mario Kart Wii',
                                           'Wii Sports Resort',
                                    'Pokemon Red/Pokemon Blue',
                                                      'Tetris',
                                       'New Super Mario Bros.',
                                                    'Wii Play',
                                   'New Super Mario Bros. Wii',
                                                   'Duck Hunt',
 ...
                                              'Carmageddon 64',
                                            'Bust-A-Move 3000',
                                                      'Breach',
                                    'Mezase!! Tsuri Master DS',
                                            'Mega Brain Boost',
     'Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shirube Kareru',
 'Eiyuu Densetsu: Sora no Kiseki Material Collection Portable',
                                                    'Plushees',
                          'Woody Woodpecker in Crazy Castle 5',
                                                  'Know How 2']
Length: 11493, dtype: str
----------------------------------------------------------------------------------------------------
Platform
31
<StringArray>
[ 'Wii',  'NES',   'GB',   'DS', 'X360',  'PS3',  'PS2', 'SNES',  'GBA',
  '3DS',  'PS4',  'N64',   'PS',   'XB',   'PC', '2600',  'PSP', 'XOne',
   'GC', 'WiiU',  'GEN',   'DC',  'PSV',  'SAT',  'SCD',   'WS',   'NG',
 'TG16',  '3DO',   'GG', 'PCFX']
Length: 31, dtype: str
----------------------------------------------------------------------------------------------------
Genre
12
<StringArray>
[      'Sports',     'Platform',       'Racing', 'Role-Playing',
       'Puzzle',         'Misc',      'Shooter',   'Simulation',
       'Action',     'Fighting',    'Adventure',     'Strategy']
Length: 12, dtype: str
----------------------------------------------------------------------------------------------------
Publisher
578
<StringArray>
[                   'Nintendo',      'Microsoft Game Studios',
        'Take-Two Interactive', 'Sony Computer Entertainment',
                  'Activision',                     'Ubisoft',
          'Bethesda Softworks',             'Electronic Arts',
                        'Sega',                  'SquareSoft',
 ...
                   'Nitroplus',         'Paradox Development',
                     'Otomate',                   'Ongakukan',
                    'Commseed',                'Inti Creates',
                      'Takuyo',          'Interchannel-Holon',
                  'Rain Games',           'UIG Entertainment']
Length: 578, dtype: str
----------------------------------------------------------------------------------------------------
Platform_Family
5
<StringArray>
['Nintendo', 'Xbox', 'PlayStation', 'PC', 'Other']
Length: 5, dtype: str
----------------------------------------------------------------------------------------------------

### Handling missing Years

In [26]:
median_year = df['Year'].median()  
df['Year'] = df['Year'].fillna(median_year)

### Handling missing Publishers

In [27]:
df['Publisher'] = df['Publisher'].fillna('Unknown')

### Convert Year to integer

In [28]:
df['Year'] = df['Year'].astype(int)

In [29]:
print(df.isnull().sum())

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [30]:
print(df.dtypes)

Rank              int64
Name                str
Platform            str
Year              int64
Genre               str
Publisher           str
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [31]:
cols= ['NA_Sales','EU_Sales','JP_Sales','Other_Sales']

In [32]:
from datasist.structdata import detect_outliers
outliers_indicies=[]

for col in cols:
   outliers_indicies = outliers_indicies + detect_outliers(data=df ,n=0, features=[col])
   
   col_median= df[col].median()

   df[col].loc[outliers_indicies] = col_median

C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_23244\387439023.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[col].loc[outliers_indicies] = col_median
C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_23244\387439023.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[col].loc[outliers_indicies] = col_median
C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_23244\387439023.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[col].loc[outliers_indicies] = col_median
C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_23244\387439023.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[col].loc[outliers_indicies] = col_median

In [33]:
print(outliers_indicies)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 215, 216, 217, 218, 220, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 243, 244, 245, 246, 247, 248, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 313, 314, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 335, 336, 337, 339, 340, 341, 342, 343, 344, 345, 346, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 378, 379, 380, 381, 382, 384, 385, 386, 387, 388, 389, 390, 391, 393, 394, 395, 396, 397, 398, 399, 400, 401, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 415, 416, 417, 418, 420, 421, 422, 423, 424, 425, 427, 428, 429, 430, 431, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 475, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 498, 499, 500, 501, 502, 503, 505, 506, 507, 508, 509, 510, 511, 512, 514, 515, 516, 517, 518, 519, 520, 522, 523, 524, 525, 526, 528, 529, 530, 532, 533, 534, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 574, 575, 576, 577, 578, 579, 580, 581, 582, 584, 585, 586, 587, 588, 590, 591, 592, 593, 594, 596, 597, 599, 600, 601, 603, 604, 605, 606, 607, 608, 609, 610, 613, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 630, 631, 632, 633, 634, 635, 636, 637, 638, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 687, 689, 690, 691, 692, 693, 694, 695, 696, 698, 702, 703, 705, 706, 707, 708, 709, 710, 711, 712, 714, 715, 716, 717, 718, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 738, 739, 741, 742, 743, 744, 747, 748, 749, 750, 751, 752, 753, 755, 756, 757, 762, 764, 765, 766, 767, 768, 769, 771, 772, 773, 774, 775, 776, 777, 778, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 792, 793, 794, 795, 796, 797, 799, 800, 801, 802, 803, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 829, 830, 831, 832, 833, 834, 836, 837, 838, 839, 840, 841, 842, 843, 845, 846, 847, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 867, 869, 870, 871, 872, 873, 874, 875, 876, 878, 880, 881, 882, 883, 884, 885, 886, 887, 889, 890, 892, 893, 894, 895, 896, 897, 898, 899, 901, 902, 903, 904, 905, 906, 907, 909, 910, 912, 913, 914, 916, 917, 919, 922, 923, 924, 925, 926, 927, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 941, 942, 943, 944, 945, 946, 949, 950, 951, 952, 953, 954, 955, 958, 959, 960, 961, 962, 963, 964, 965, 966, 968, 970, 971, 973, 978, 979, 980, 982, 984, 985, 986, 987, 988, 989, 990, 991, 993, 994, 995, 996, 997, 998, 999, 1002, 1003, 1004, 1005, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1038, 1039, 1041, 1042, 1043, 1044, 1045, 1047, 1048, 1051, 1053, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1078, 1079, 1080, 1081, 1082, 1083, 1085, 1086, 1088, 1089, 1090, 1092, 1093, 1094, 1095, 1096, 1097, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1111, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1121, 1123, 1125, 1128, 1129, 1130, 1131, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1144, 1146, 1147, 1148, 1150, 1151, 1153, 1154, 1157, 1158, 1160, 1161, 1163, 1165, 1166, 1167, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1179, 1181, 1182, 1183, 1185, 1186, 1188, 1190, 1192, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1202, 1203, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1221, 1222, 1223, 1225, 1226, 1227, 1228, 1230, 1232, 1235, 1236, 1239, 1240, 1241, 1242, 1243, 1246, 1248, 1250, 1251, 1252, 1253, 1254, 1255, 1257, 1258, 1259, 1261, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1273, 1274, 1279, 1280, 1281, 1282, 1283, 1284, 1287, 1288, 1289, 1290, 1292, 1293, 1294, 1295, 1298, 1299, 1300, 1301, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1312, 1316, 1317, 1318, 1319, 1327, 1328, 1330, 1332, 1334, 1338, 1339, 1340, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1352, 1354, 1355, 1356, 1357, 1358, 1359, 1362, 1363, 1367, 1368, 1369, 1370, 1371, 1372, 1374, 1375, 1377, 1378, 1379, 1380, 1382, 1384, 1388, 1391, 1393, 1394, 1396, 1398, 1399, 1403, 1404, 1407, 1408, 1409, 1410, 1411, 1415, 1418, 1419, 1422, 1423, 1424, 1425, 1429, 1431, 1432, 1433, 1434, 1437, 1439, 1442, 1443, 1444, 1446, 1447, 1448, 1450, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1479, 1480, 1482, 1483, 1484, 1488, 1490, 1491, 1492, 1494, 1495, 1496, 1497, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1516, 1519, 1520, 1522, 1526, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1543, 1544, 1545, 1546, 1547, 1549, 1552, 1553, 1554, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1565, 1566, 1574, 1579, 1580, 1582, 1583, 1585, 1589, 1591, 1592, 1593, 1594, 1596, 1597, 1598, 1599, 1601, 1602, 1604, 1605, 1607, 1609, 1613, 1616, 1618, 1621, 1622, 1624, 1627, 1628, 1629, 1636, 1637, 1641, 1642, 1644, 1645, 1646, 1647, 1651, 1652, 1653, 1655, 1656, 1657, 1659, 1661, 1662, 1663, 1668, 1671, 1672, 1677, 1679, 1681, 1686, 1689, 1691, 1693, 1694, 1695, 1696, 1697, 1699, 1700, 1701, 1703, 1704, 1705, 1711, 1714, 1718, 1719, 1720, 1721, 1726, 1728, 1731, 1733, 1735, 1737, 1738, 1740, 1744, 1748, 1750, 1752, 1754, 1758, 1766, 1768, 1774, 1779, 1782, 1784, 1787, 1790, 1791, 1795, 1796, 1798, 1800, 1801, 1803, 1805, 1807, 1810, 1811, 1814, 1815, 1816, 1817, 1820, 1823, 1824, 1825, 1826, 1830, 1831, 1833, 1835, 1836, 1837, 1838, 1841, 1848, 1851, 1852, 1862, 1871, 1874, 1875, 1877, 1879, 1880, 1881, 1883, 1884, 1887, 1892, 1897, 1901, 1905, 1907, 1910, 1912, 1913, 1914, 1916, 1917, 1919, 1920, 1927, 1929, 1933, 1938, 1942, 1944, 1949, 1953, 1954, 1956, 1957, 1959, 1965, 1966, 1969, 1978, 1979, 1984, 1998, 2002, 2003, 2007, 2008, 2013, 2015, 2017, 2019, 2022, 2023, 2025, 2028, 2030, 2036, 2037, 2045, 2046, 2054, 2059, 2060, 2062, 2064, 2066, 2073, 2076, 2078, 2081, 2083, 2084, 2089, 2092, 2095, 2098, 2101, 2104, 2108, 2111, 2112, 2113, 2123, 2124, 2125, 2128, 2130, 2132, 2138, 2139, 2143, 2144, 2148, 2153, 2157, 2167, 2172, 2174, 2176, 2178, 2183, 2190, 2191, 2194, 2198, 2199, 2201, 2207, 2208, 2210, 2213, 2217, 2220, 2222, 2230, 2231, 2232, 2235, 2236, 2237, 2239, 2248, 2254, 2255, 2258, 2266, 2267, 2271, 2274, 2283, 2286, 2287, 2290, 2298, 2299, 2311, 2312, 2313, 2318, 2320, 2321, 2323, 2324, 2327, 2328, 2332, 2337, 2346, 2359, 2361, 2374, 2377, 2380, 2382, 2385, 2386, 2387, 2392, 2397, 2399, 2406, 2419, 2423, 2432, 2433, 2436, 2438, 2442, 2453, 2457, 2458, 2461, 2462, 2465, 2484, 2488, 2493, 2494, 2495, 2498, 2505, 2507, 2508, 2510, 2512, 2514, 2515, 2516, 2529, 2530, 2532, 2539, 2540, 2546, 2555, 2559, 2561, 2566, 2584, 2587, 2596, 2597, 2600, 2603, 2608, 2609, 2612, 2617, 2618, 2622, 2628, 2629, 2637, 2640, 2648, 2652, 2659, 2660, 2663, 2664, 2668, 2669, 2672, 2676, 2678, 2692, 2700, 2710, 2713, 2730, 2742, 2747, 2755, 2770, 2776, 2777, 2778, 2793, 2801, 2806, 2807, 2809, 2811, 2839, 2843, 2846, 2849, 2858, 2860, 2874, 2878, 2897, 2910, 2936, 2940, 2952, 2977, 2981, 2995, 3044, 3079, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 208, 209, 210, 212, 213, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 241, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 259, 260, 261, 262, 263, 264, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 280, 282, 283, 284, 285, 286, 287, 288, 289, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 339, 340, 341, 342, 343, 344, 345, 346, 347, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 384, 385, 386, 387, 388, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 415, 416, 417, 418, 420, 422, 423, 424, 425, 427, 428, 429, 430, 431, 432, 433, 434, 436, 437, 438, 439, 441, 442, 443, 444, 445, 447, 448, 449, 450, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 507, 508, 509, 510, 511, 512, 513, 514, 515, 517, 518, 519, 520, 521, 522, 523, 524, 525, 528, 529, 530, 532, 533, 535, 536, 537, 538, 539, 540, 541, 542, 543, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 556, 558, 559, 560, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 574, 575, 576, 577, 578, 579, 581, 582, 583, 585, 586, 587, 588, 589, 590, 592, 593, 594, 596, 597, 598, 599, 601, 604, 605, 608, 609, 610, 612, 616, 617, 618, 619, 620, 621, 622, 623, 624, 626, 627, 628, 632, 633, 634, 635, 636, 637, 638, 639, 642, 643, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 663, 666, 667, 669, 671, 672, 674, 675, 677, 678, 679, 680, 682, 683, 684, 685, 686, 687, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 702, 703, 704, 705, 706, 707, 709, 710, 711, 712, 713, 714, 715, 718, 719, 720, 721, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 736, 738, 739, 740, 741, 742, 744, 745, 748, 752, 753, 755, 756, 757, 758, 760, 761, 764, 765, 767, 769, 770, 771, 774, 775, 777, 778, 779, 780, 781, 782, 784, 786, 787, 789, 790, 792, 793, 796, 797, 798, 799, 800, 801, 802, 803, 804, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 825, 826, 828, 830, 831, 833, 834, 835, 837, 838, 840, 843, 844, 845, 846, 847, 848, 850, 851, 852, 853, 854, 856, 857, 858, 859, 860, 861, 862, 863, 865, 866, 867, 870, 871, 872, 873, 874, 876, 877, 879, 880, 882, 883, 884, 885, 886, 887, 889, 891, 893, 894, 895, 896, 897, 898, 899, 901, 903, 904, 905, 906, 907, 908, 909, 911, 912, 913, 914, 916, 917, 919, 920, 922, 923, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 939, 940, 941, 944, 945, 946, 947, 949, 950, 951, 952, 955, 957, 958, 959, 960, 961, 963, 966, 967, 968, 969, 970, 971, 973, 974, 975, 976, 977, 978, 979, 980, 981, 985, 986, 987, 988, 989, 990, 991, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1004, 1005, 1006, 1007, 1009, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1022, 1023, 1024, 1025, 1026, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1036, 1037, 1040, 1042, 1043, 1044, 1045, 1047, 1049, 1051, 1052, 1055, 1057, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1069, 1070, 1071, 1072, 1073, 1075, 1077, 1079, 1080, 1082, 1083, 1084, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1108, 1109, 1111, 1114, 1116, 1118, 1120, 1121, 1122, 1124, 1126, 1127, 1128, 1129, 1132, 1133, 1134, 1135, 1138, 1139, 1140, 1141, 1144, 1145, 1147, 1148, 1149, 1151, 1152, 1154, 1156, 1157, 1159, 1160, 1161, 1162, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1177, 1178, 1179, 1181, 1182, 1184, 1185, 1186, 1189, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1206, 1207, 1208, 1209, 1211, 1212, 1214, 1216, 1217, 1218, 1219, 1220, 1221, 1223, 1224, 1226, 1227, 1228, 1229, 1230, 1231, 1237, 1238, 1239, 1242, 1243, 1244, 1247, 1251, 1252, 1253, 1254, 1256, 1257, 1261, 1263, 1266, 1267, 1268, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1280, 1281, 1282, 1284, 1285, 1286, 1287, 1289, 1291, 1293, 1294, 1296, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1307, 1309, 1310, 1311, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1328, 1331, 1332, 1333, 1334, 1335, 1337, 1338, 1339, 1341, 1342, 1343, 1345, 1346, 1347, 1348, 1349, 1352, 1354, 1355, 1359, 1362, 1363, 1365, 1366, 1367, 1368, 1369, 1370, 1372, 1373, 1374, 1375, 1376, 1378, 1379, 1380, 1383, 1384, 1386, 1387, 1388, 1389, 1390, 1392, 1396, 1397, 1398, 1399, 1400, 1402, 1403, 1404, 1405, 1406, 1407, 1409, 1410, 1411, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1423, 1424, 1425, 1430, 1431, 1432, 1433, 1434, 1436, 1438, 1440, 1441, 1442, 1443, 1446, 1447, 1448, 1450, 1452, 1453, 1454, 1459, 1462, 1465, 1467, 1468, 1469, 1470, 1471, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1482, 1483, 1484, 1485, 1487, 1488, 1489, 1492, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1502, 1503, 1505, 1506, 1507, 1509, 1510, 1512, 1514, 1515, 1517, 1519, 1522, 1523, 1524, 1525, 1526, 1528, 1531, 1532, 1533, 1535, 1538, 1539, 1540, 1541, 1543, 1545, 1547, 1548, 1549, 1550, 1551, 1554, 1555, 1558, 1559, 1561, 1563, 1564, 1565, 1566, 1569, 1571, 1574, 1575, 1576, 1577, 1578, 1580, 1581, 1583, 1586, 1590, 1594, 1595, 1598, 1602, 1603, 1604, 1605, 1609, 1610, 1611, 1612, 1614, 1615, 1616, 1617, 1619, 1621, 1622, 1625, 1629, 1630, 1631, 1632, 1633, 1636, 1637, 1639, 1640, 1641, 1645, 1647, 1648, 1649, 1650, 1653, 1654, 1656, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1670, 1671, 1672, 1673, 1678, 1679, 1680, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1692, 1697, 1698, 1702, 1704, 1707, 1711, 1712, 1713, 1717, 1718, 1719, 1722, 1723, 1724, 1725, 1727, 1728, 1730, 1731, 1733, 1734, 1735, 1736, 1739, 1740, 1741, 1742, 1745, 1746, 1748, 1749, 1750, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1767, 1768, 1769, 1773, 1776, 1778, 1779, 1782, 1783, 1788, 1789, 1794, 1795, 1796, 1797, 1798, 1800, 1802, 1803, 1805, 1806, 1808, 1810, 1811, 1812, 1814, 1815, 1816, 1818, 1820, 1821, 1822, 1824, 1826, 1828, 1829, 1832, 1833, 1834, 1836, 1838, 1842, 1843, 1845, 1846, 1847, 1849, 1850, 1852, 1853, 1854, 1855, 1860, 1863, 1864, 1865, 1867, 1870, 1871, 1872, 1875, 1876, 1882, 1884, 1885, 1887, 1888, 1889, 1890, 1891, 1893, 1894, 1895, 1896, 1898, 1899, 1900, 1902, 1903, 1904, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1915, 1920, 1921, 1922, 1924, 1926, 1928, 1930, 1931, 1932, 1933, 1935, 1936, 1937, 1939, 1940, 1941, 1942, 1943, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1955, 1958, 1959, 1960, 1961, 1962, 1964, 1967, 1968, 1970, 1975, 1976, 1977, 1980, 1981, 1982, 1983, 1984, 1987, 1988, 1989, 1990, 1991, 1992, 1994, 1995, 1996, 1999, 2003, 2004, 2005, 2007, 2009, 2010, 2011, 2012, 2014, 2016, 2018, 2019, 2021, 2025, 2026, 2027, 2029, 2031, 2034, 2035, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2047, 2048, 2051, 2052, 2053, 2055, 2057, 2065, 2067, 2068, 2069, 2070, 2071, 2075, 2077, 2078, 2079, 2080, 2081, 2085, 2086, 2087, 2088, 2090, 2091, 2092, 2093, 2094, 2096, 2099, 2100, 2102, 2103, 2105, 2106, 2110, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2127, 2129, 2131, 2135, 2136, 2137, 2140, 2141, 2145, 2146, 2147, 2150, 2151, 2155, 2156, 2159, 2160, 2161, 2163, 2164, 2166, 2168, 2169, 2170, 2171, 2173, 2175, 2177, 2179, 2180, 2184, 2185, 2186, 2187, 2188, 2189, 2192, 2193, 2195, 2196, 2200, 2202, 2203, 2204, 2205, 2211, 2212, 2214, 2216, 2218, 2219, 2221, 2223, 2224, 2225, 2227, 2228, 2229, 2238, 2240, 2243, 2244, 2245, 2246, 2247, 2249, 2250, 2251, 2256, 2257, 2260, 2262, 2263, 2265, 2268, 2272, 2273, 2275, 2276, 2279, 2281, 2282, 2285, 2291, 2292, 2293, 2294, 2297, 2300, 2301, 2302, 2303, 2304, 2305, 2307, 2308, 2310, 2314, 2315, 2316, 2317, 2319, 2322, 2325, 2326, 2329, 2331, 2338, 2340, 2341, 2342, 2344, 2345, 2347, 2351, 2352, 2354, 2355, 2356, 2357, 2358, 2363, 2366, 2367, 2369, 2370, 2371, 2372, 2375, 2376, 2378, 2381, 2383, 2384, 2388, 2389, 2390, 2391, 2393, 2394, 2395, 2396, 2400, 2401, 2403, 2405, 2408, 2410, 2411, 2412, 2413, 2415, 2416, 2418, 2420, 2421, 2424, 2427, 2429, 2430, 2431, 2434, 2440, 2441, 2443, 2446, 2447, 2451, 2452, 2455, 2459, 2460, 2464, 2468, 2470, 2471, 2473, 2475, 2476, 2478, 2479, 2480, 2483, 2491, 2497, 2499, 2501, 2502, 2503, 2509, 2517, 2518, 2520, 2521, 2522, 2524, 2525, 2527, 2533, 2538, 2542, 2545, 2548, 2549, 2551, 2553, 2554, 2563, 2564, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2575, 2576, 2578, 2579, 2580, 2582, 2583, 2586, 2593, 2595, 2599, 2605, 2606, 2619, 2620, 2623, 2624, 2627, 2630, 2633, 2634, 2636, 2638, 2639, 2641, 2642, 2643, 2644, 2649, 2650, 2654, 2655, 2656, 2657, 2661, 2662, 2665, 2666, 2670, 2679, 2680, 2683, 2685, 2688, 2689, 2690, 2691, 2693, 2699, 2701, 2702, 2708, 2709, 2711, 2712, 2716, 2718, 2719, 2722, 2723, 2724, 2725, 2728, 2735, 2740, 2741, 2745, 2748, 2751, 2753, 2756, 2758, 2760, 2764, 2766, 2768, 2771, 2773, 2774, 2775, 2779, 2781, 2782, 2783, 2787, 2788, 2797, 2800, 2803, 2808, 2810, 2817, 2818, 2820, 2821, 2824, 2825, 2828, 2838, 2841, 2842, 2844, 2845, 2848, 2854, 2855, 2856, 2864, 2886, 2889, 2891, 2899, 2901, 2902, 2908, 2918, 2921, 2929, 2942, 2947, 2950, 2953, 2961, 2963, 2965, 2968, 2969, 2979, 2980, 2983, 2987, 2990, 2994, 2996, 2997, 3001, 3006, 3012, 3018, 3024, 3026, 3027, 3028, 3029, 3032, 3034, 3035, 3036, 3038, 3040, 3043, 3048, 3069, 3073, 3080, 3091, 3105, 3117, 3132, 3139, 3141, 3148, 3149, 3152, 3154, 3161, 3165, 3170, 3172, 3173, 3181, 3188, 3189, 3192, 3202, 3212, 3219, 3222, 3233, 3247, 3250, 3260, 3282, 3287, 3303, 3346, 3351, 3369, 3382, 3384, 3385, 3386, 3390

In [34]:
len(outliers_indicies)

7852

In [35]:
len(set(outliers_indicies))

4580

In [36]:
outliers_indicies = list(set(outliers_indicies))
len(outliers_indicies)

4580

In [37]:
def custom_detect_outlier(dataframe, col, lower_bound_percentage : float, upper_bound_percentage : float):

    'Return list of outliers indices of the given percentages'

    # Detect lower and upper bounds
    lower_bound = dataframe[col].quantile(lower_bound_percentage)
    upper_bound = dataframe[col].quantile(upper_bound_percentage)

    # Return outlier indices
    outliers_indices = dataframe[(dataframe[col] < lower_bound) | (dataframe[col] > upper_bound)].index
    return outliers_indicies

In [38]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [39]:
print(custom_detect_outlier(dataframe= df, col= 'NA_Sales', lower_bound_percentage= 0.1, upper_bound_percentage= 0.9))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 8890, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 9103, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 8348, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 9434, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 8415, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 8421, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 8424, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 9669, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 8442, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 8529, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 8547, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 8552, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 10393, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2074, 2252, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 8592, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 8558, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 10231, 2331, 2332, 2333, 8559, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 10235, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 8609, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 8617, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 9865, 2423, 2424, 2425, 2427, 10191, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2428, 2438, 2439, 2440, 2441, 2442, 2443, 2437, 2445, 2446, 2447, 2448, 2449, 8238, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 8564, 2464, 2465, 2466, 10259, 2468, 2463, 2470, 2471, 2472, 2473, 2475, 2476, 8633, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 8634, 2477, 2487, 2488, 2486, 2490, 2491, 2492, 2493, 2494, 2495, 10265, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2505, 8639, 2507, 2508, 2509, 2510, 10268, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 8642, 2524, 2525, 2526, 2527, 2523, 2529, 2530, 2531, 2532, 2533, 2534, 8644, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 8242, 2557, 2559, 2561, 8650, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 9871, 2575, 2576, 10281, 2578, 2579, 2580, 2577, 2582, 2583, 2584, 2585, 2586, 2587, 8467, 2590, 2591, 2592, 2593, 2595, 2596, 2597, 8657, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 8658, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2607, 2617, 2618, 2619, 2620, 8662, 2622, 2623, 2624, 8245, 2626, 2627, 2628, 2629, 2630, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 8667, 2648, 2649, 2650, 2651, 2652, 8668, 2654, 2655, 2656, 2657, 10297, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2674, 2676, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 10201, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 8676, 2696, 2695, 2699, 2700, 2701, 2702, 8248, 2704, 8678, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2716, 2717, 2718, 2719, 10309, 2722, 2723, 2724, 2725, 10311, 2727, 2728, 10203, 2730, 2731, 8575, 2732, 2734, 2735, 2733, 2737, 2740, 2741, 2742, 2744, 2745, 2746, 2747, 2748, 1715, 2750, 2751, 10316, 2753, 2754, 2755, 2756, 8689, 2758, 2760, 10318, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 8693, 2781, 2782, 2783, 2784, 9791, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 8696, 2800, 2801, 2802, 2803, 2804, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 8700, 2814, 2817, 2818, 2820, 2821, 2822, 10330, 2824, 2825, 10331, 2828, 2829, 2831, 10099, 8704, 2837, 2838, 2839, 2841, 2842, 2843, 2844, 2845, 2846, 2848, 2849, 2850, 2851, 2852, 8254, 2854, 2855, 2856, 2858, 2859, 2860, 2862, 8580, 2864, 2865, 2866, 2868, 2874, 2875, 2878, 2882, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2897, 8717, 2899, 2900, 2901, 2902, 2905, 2906, 2908, 2910, 2918, 9885, 2921, 2922, 8722, 10350, 2926, 10351, 2929, 2932, 2933, 2936, 2937, 2938, 2940, 2942, 2944, 2947, 2950, 2952, 2953, 2955, 2956, 10357, 2960, 2961, 8584, 2963, 2965, 10118, 2967, 2968, 2969, 2973, 2976, 2977, 2978, 2979, 2980, 2981, 8259, 2983, 2986, 2987, 2988, 8490, 2990, 2992, 2993, 2994, 2995, 2996, 2997, 3000, 3001, 3002, 3006, 3007, 3008, 8739, 10214, 3011, 3012, 3018, 10369, 3020, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 10371, 3031, 3032, 3034, 3035, 3036, 3038, 3040, 3042, 3043, 3044, 3045, 3047, 3048, 10375, 3050, 3057, 3064, 3066, 3067, 3069, 3073, 3074, 3075, 10380, 3076, 10381, 3079, 3080, 3081, 3083, 3084, 3086, 3089, 3090, 3091, 10119, 10384, 3096, 3100, 3101, 9892, 10386, 3104, 3105, 3103, 3109, 8759, 10388, 3114, 3116, 3117, 8761, 3121, 3123, 3125, 3126, 3127, 3130, 3131, 3132, 3134, 3138, 3139, 3141, 3148, 3149, 10395, 3152, 3154, 10397, 3161, 3162, 3163, 3165, 10399, 3169, 3170, 9839, 3172, 3173, 3178, 8267, 3181, 3186, 3188, 3189, 3192, 3194, 10405, 3201, 3202, 3204, 3209, 3212, 3213, 10408, 3214, 3219, 3221, 3222, 3223, 10410, 3225, 3226, 3228, 8783, 3232, 3233, 10412, 3236, 3237, 8785, 3242, 3243, 3247, 3250, 3251, 3255, 9774, 3257, 3260, 8789, 8596, 3265, 3268, 3269, 3271, 3273, 3274, 3275, 9899, 3278, 3279, 3281, 3282, 3283, 3285, 3286, 3287, 3289, 3290, 3302, 3303, 3304, 3306, 8799, 3311, 3313, 3317, 3333, 3335, 8599, 3341, 3346, 3347, 3351, 3352, 3353, 3355, 8808, 3357, 3360, 3361, 8809, 3365, 3366, 8810, 3368, 3369, 8811, 3372, 9903, 3380, 3381, 3382, 10229, 3384, 3385, 3386, 3387, 3389, 3390, 3394, 3396, 3398, 3399, 9904, 3401, 8817, 3402, 3404, 3405, 8276, 8602, 3415, 3416, 3419, 3420, 3425, 9796, 3427, 2309, 8277, 3432, 3434, 3435, 3437, 3438, 3443, 3448, 3450, 3451, 3453, 8278, 3455, 3457, 10232, 3464, 3465, 3466, 3467, 8830, 3470, 3471, 9907, 3476, 3477, 3481, 3484, 3485, 3487, 8834, 3495, 3500, 3503, 3504, 3505, 10234, 3512, 3513, 3516, 3520, 3521, 3522, 9909, 3526, 701, 8281, 3532, 3535, 3538, 3544, 3547, 8846, 3550, 9797, 9910, 8282, 3555, 3556, 3558, 3559, 3562, 8850, 3568, 3576, 8852, 8854, 3591, 3593, 3594, 3596, 3598, 3599, 3607, 3609, 3612, 3615, 3619, 8861, 3623, 3628, 3633, 3636, 3637, 3640, 3641, 8865, 3647, 3648, 3649, 3656, 3657, 3662, 3666, 3667, 3669, 3672, 3674, 3677, 3686, 3687, 3688, 3689, 3693, 3694, 3695, 8875, 3698, 3700, 3703, 3705, 3707, 3708, 3709, 10242, 3718, 3719, 3721, 3722, 3723, 3724, 8881, 3726, 3728, 3731, 3732, 8496, 3741, 3743, 3746, 3749, 3752, 3755, 3756, 3759, 3763, 3764, 3771, 9919, 3780, 3781, 3782, 8893, 3784, 3785, 3787, 3789, 3800, 9920, 3806, 3811, 3812, 3815, 3820, 3822, 3823, 10190, 3827, 3829, 3832, 8293, 3837, 8904, 3840, 10247, 3844, 3846, 3847, 3848, 3851, 3854, 3855, 9922, 8908, 3864, 3865, 8909, 10248, 8910, 3870, 8911, 3877, 3878, 3883, 8913, 3885, 3888, 3890, 3895, 3897, 8916, 3902, 3903, 3907, 3908, 3915, 3918, 3920, 3921, 3923, 9800, 3926, 8922, 3931, 3934, 8297, 3945, 3948, 3955, 3958, 3959, 3960, 3973, 3979, 3980, 3981, 3987, 3988, 3997, 4002, 4003, 8937, 4006, 4007, 4017, 4020, 8940, 4026, 4027, 9929, 8301, 8943, 4038, 4039, 4040, 4041, 4044, 4045, 4050, 8946, 4053, 4057, 4058, 4059, 4060, 4061, 4062, 4065, 8949, 4069, 8950, 4071, 4073, 4074, 4076, 4081, 4084, 8303, 4087, 4091, 4093, 4097, 4107, 4109, 8304, 8499, 8958, 4111, 4115, 8959, 4122, 9933, 8962, 4132, 4133, 4134, 4138, 4140, 4145, 4146, 4150, 8306, 4160, 4168, 4170, 4171, 4174, 4175, 4178, 4179, 4180, 4181, 4182, 8973, 4189, 4192, 8975, 4201, 4205, 4206, 4207, 9936, 4208, 4213, 4215, 10128, 4218, 8980, 4229, 8309, 4240, 4241, 4242, 8984, 4244, 4247, 8987, 4261, 4273, 4274, 4280, 4282, 4287, 8993, 4290, 4293, 4294, 4296, 4299, 4306, 4307, 4308, 4310, 4316, 4318, 4322, 9000, 4324, 4325, 9002, 4340, 4341, 9004, 4352, 10161, 9007, 4358, 4359, 4360, 4363, 4368, 4372, 4373, 4379, 4381, 4383, 4384, 4386, 9013, 4391, 9014, 4395, 4399, 4400, 4405, 4413, 2506, 4431, 9022, 8317, 4437, 4440, 4441, 2511, 4444, 4447, 4450, 4451, 4457, 8318, 4461, 4463, 

In [40]:
print(custom_detect_outlier(dataframe= df, col= 'EU_Sales', lower_bound_percentage= 0.1, upper_bound_percentage= 0.9))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 8890, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 9103, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 8348, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 9434, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 8415, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 8421, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 8424, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 9669, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 8442, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 8529, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 8547, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 8552, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 10393, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2074, 2252, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 8592, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 8558, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 10231, 2331, 2332, 2333, 8559, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 10235, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 8609, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 8617, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 9865, 2423, 2424, 2425, 2427, 10191, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2428, 2438, 2439, 2440, 2441, 2442, 2443, 2437, 2445, 2446, 2447, 2448, 2449, 8238, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 8564, 2464, 2465, 2466, 10259, 2468, 2463, 2470, 2471, 2472, 2473, 2475, 2476, 8633, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 8634, 2477, 2487, 2488, 2486, 2490, 2491, 2492, 2493, 2494, 2495, 10265, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2505, 8639, 2507, 2508, 2509, 2510, 10268, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 8642, 2524, 2525, 2526, 2527, 2523, 2529, 2530, 2531, 2532, 2533, 2534, 8644, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 8242, 2557, 2559, 2561, 8650, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 9871, 2575, 2576, 10281, 2578, 2579, 2580, 2577, 2582, 2583, 2584, 2585, 2586, 2587, 8467, 2590, 2591, 2592, 2593, 2595, 2596, 2597, 8657, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 8658, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2607, 2617, 2618, 2619, 2620, 8662, 2622, 2623, 2624, 8245, 2626, 2627, 2628, 2629, 2630, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 8667, 2648, 2649, 2650, 2651, 2652, 8668, 2654, 2655, 2656, 2657, 10297, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2674, 2676, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 10201, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 8676, 2696, 2695, 2699, 2700, 2701, 2702, 8248, 2704, 8678, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2716, 2717, 2718, 2719, 10309, 2722, 2723, 2724, 2725, 10311, 2727, 2728, 10203, 2730, 2731, 8575, 2732, 2734, 2735, 2733, 2737, 2740, 2741, 2742, 2744, 2745, 2746, 2747, 2748, 1715, 2750, 2751, 10316, 2753, 2754, 2755, 2756, 8689, 2758, 2760, 10318, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 8693, 2781, 2782, 2783, 2784, 9791, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 8696, 2800, 2801, 2802, 2803, 2804, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 8700, 2814, 2817, 2818, 2820, 2821, 2822, 10330, 2824, 2825, 10331, 2828, 2829, 2831, 10099, 8704, 2837, 2838, 2839, 2841, 2842, 2843, 2844, 2845, 2846, 2848, 2849, 2850, 2851, 2852, 8254, 2854, 2855, 2856, 2858, 2859, 2860, 2862, 8580, 2864, 2865, 2866, 2868, 2874, 2875, 2878, 2882, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2897, 8717, 2899, 2900, 2901, 2902, 2905, 2906, 2908, 2910, 2918, 9885, 2921, 2922, 8722, 10350, 2926, 10351, 2929, 2932, 2933, 2936, 2937, 2938, 2940, 2942, 2944, 2947, 2950, 2952, 2953, 2955, 2956, 10357, 2960, 2961, 8584, 2963, 2965, 10118, 2967, 2968, 2969, 2973, 2976, 2977, 2978, 2979, 2980, 2981, 8259, 2983, 2986, 2987, 2988, 8490, 2990, 2992, 2993, 2994, 2995, 2996, 2997, 3000, 3001, 3002, 3006, 3007, 3008, 8739, 10214, 3011, 3012, 3018, 10369, 3020, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 10371, 3031, 3032, 3034, 3035, 3036, 3038, 3040, 3042, 3043, 3044, 3045, 3047, 3048, 10375, 3050, 3057, 3064, 3066, 3067, 3069, 3073, 3074, 3075, 10380, 3076, 10381, 3079, 3080, 3081, 3083, 3084, 3086, 3089, 3090, 3091, 10119, 10384, 3096, 3100, 3101, 9892, 10386, 3104, 3105, 3103, 3109, 8759, 10388, 3114, 3116, 3117, 8761, 3121, 3123, 3125, 3126, 3127, 3130, 3131, 3132, 3134, 3138, 3139, 3141, 3148, 3149, 10395, 3152, 3154, 10397, 3161, 3162, 3163, 3165, 10399, 3169, 3170, 9839, 3172, 3173, 3178, 8267, 3181, 3186, 3188, 3189, 3192, 3194, 10405, 3201, 3202, 3204, 3209, 3212, 3213, 10408, 3214, 3219, 3221, 3222, 3223, 10410, 3225, 3226, 3228, 8783, 3232, 3233, 10412, 3236, 3237, 8785, 3242, 3243, 3247, 3250, 3251, 3255, 9774, 3257, 3260, 8789, 8596, 3265, 3268, 3269, 3271, 3273, 3274, 3275, 9899, 3278, 3279, 3281, 3282, 3283, 3285, 3286, 3287, 3289, 3290, 3302, 3303, 3304, 3306, 8799, 3311, 3313, 3317, 3333, 3335, 8599, 3341, 3346, 3347, 3351, 3352, 3353, 3355, 8808, 3357, 3360, 3361, 8809, 3365, 3366, 8810, 3368, 3369, 8811, 3372, 9903, 3380, 3381, 3382, 10229, 3384, 3385, 3386, 3387, 3389, 3390, 3394, 3396, 3398, 3399, 9904, 3401, 8817, 3402, 3404, 3405, 8276, 8602, 3415, 3416, 3419, 3420, 3425, 9796, 3427, 2309, 8277, 3432, 3434, 3435, 3437, 3438, 3443, 3448, 3450, 3451, 3453, 8278, 3455, 3457, 10232, 3464, 3465, 3466, 3467, 8830, 3470, 3471, 9907, 3476, 3477, 3481, 3484, 3485, 3487, 8834, 3495, 3500, 3503, 3504, 3505, 10234, 3512, 3513, 3516, 3520, 3521, 3522, 9909, 3526, 701, 8281, 3532, 3535, 3538, 3544, 3547, 8846, 3550, 9797, 9910, 8282, 3555, 3556, 3558, 3559, 3562, 8850, 3568, 3576, 8852, 8854, 3591, 3593, 3594, 3596, 3598, 3599, 3607, 3609, 3612, 3615, 3619, 8861, 3623, 3628, 3633, 3636, 3637, 3640, 3641, 8865, 3647, 3648, 3649, 3656, 3657, 3662, 3666, 3667, 3669, 3672, 3674, 3677, 3686, 3687, 3688, 3689, 3693, 3694, 3695, 8875, 3698, 3700, 3703, 3705, 3707, 3708, 3709, 10242, 3718, 3719, 3721, 3722, 3723, 3724, 8881, 3726, 3728, 3731, 3732, 8496, 3741, 3743, 3746, 3749, 3752, 3755, 3756, 3759, 3763, 3764, 3771, 9919, 3780, 3781, 3782, 8893, 3784, 3785, 3787, 3789, 3800, 9920, 3806, 3811, 3812, 3815, 3820, 3822, 3823, 10190, 3827, 3829, 3832, 8293, 3837, 8904, 3840, 10247, 3844, 3846, 3847, 3848, 3851, 3854, 3855, 9922, 8908, 3864, 3865, 8909, 10248, 8910, 3870, 8911, 3877, 3878, 3883, 8913, 3885, 3888, 3890, 3895, 3897, 8916, 3902, 3903, 3907, 3908, 3915, 3918, 3920, 3921, 3923, 9800, 3926, 8922, 3931, 3934, 8297, 3945, 3948, 3955, 3958, 3959, 3960, 3973, 3979, 3980, 3981, 3987, 3988, 3997, 4002, 4003, 8937, 4006, 4007, 4017, 4020, 8940, 4026, 4027, 9929, 8301, 8943, 4038, 4039, 4040, 4041, 4044, 4045, 4050, 8946, 4053, 4057, 4058, 4059, 4060, 4061, 4062, 4065, 8949, 4069, 8950, 4071, 4073, 4074, 4076, 4081, 4084, 8303, 4087, 4091, 4093, 4097, 4107, 4109, 8304, 8499, 8958, 4111, 4115, 8959, 4122, 9933, 8962, 4132, 4133, 4134, 4138, 4140, 4145, 4146, 4150, 8306, 4160, 4168, 4170, 4171, 4174, 4175, 4178, 4179, 4180, 4181, 4182, 8973, 4189, 4192, 8975, 4201, 4205, 4206, 4207, 9936, 4208, 4213, 4215, 10128, 4218, 8980, 4229, 8309, 4240, 4241, 4242, 8984, 4244, 4247, 8987, 4261, 4273, 4274, 4280, 4282, 4287, 8993, 4290, 4293, 4294, 4296, 4299, 4306, 4307, 4308, 4310, 4316, 4318, 4322, 9000, 4324, 4325, 9002, 4340, 4341, 9004, 4352, 10161, 9007, 4358, 4359, 4360, 4363, 4368, 4372, 4373, 4379, 4381, 4383, 4384, 4386, 9013, 4391, 9014, 4395, 4399, 4400, 4405, 4413, 2506, 4431, 9022, 8317, 4437, 4440, 4441, 2511, 4444, 4447, 4450, 4451, 4457, 8318, 4461, 4463, 

In [41]:
print(custom_detect_outlier(dataframe= df, col= 'JP_Sales', lower_bound_percentage= 0.1, upper_bound_percentage= 0.9))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 8890, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 9103, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 8348, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 9434, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 8415, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 8421, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 8424, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 9669, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 8442, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 8529, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 8547, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 8552, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 10393, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2074, 2252, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 8592, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 8558, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 10231, 2331, 2332, 2333, 8559, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 10235, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 8609, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 8617, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 9865, 2423, 2424, 2425, 2427, 10191, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2428, 2438, 2439, 2440, 2441, 2442, 2443, 2437, 2445, 2446, 2447, 2448, 2449, 8238, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 8564, 2464, 2465, 2466, 10259, 2468, 2463, 2470, 2471, 2472, 2473, 2475, 2476, 8633, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 8634, 2477, 2487, 2488, 2486, 2490, 2491, 2492, 2493, 2494, 2495, 10265, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2505, 8639, 2507, 2508, 2509, 2510, 10268, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 8642, 2524, 2525, 2526, 2527, 2523, 2529, 2530, 2531, 2532, 2533, 2534, 8644, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 8242, 2557, 2559, 2561, 8650, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 9871, 2575, 2576, 10281, 2578, 2579, 2580, 2577, 2582, 2583, 2584, 2585, 2586, 2587, 8467, 2590, 2591, 2592, 2593, 2595, 2596, 2597, 8657, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 8658, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2607, 2617, 2618, 2619, 2620, 8662, 2622, 2623, 2624, 8245, 2626, 2627, 2628, 2629, 2630, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 8667, 2648, 2649, 2650, 2651, 2652, 8668, 2654, 2655, 2656, 2657, 10297, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2674, 2676, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 10201, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 8676, 2696, 2695, 2699, 2700, 2701, 2702, 8248, 2704, 8678, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2716, 2717, 2718, 2719, 10309, 2722, 2723, 2724, 2725, 10311, 2727, 2728, 10203, 2730, 2731, 8575, 2732, 2734, 2735, 2733, 2737, 2740, 2741, 2742, 2744, 2745, 2746, 2747, 2748, 1715, 2750, 2751, 10316, 2753, 2754, 2755, 2756, 8689, 2758, 2760, 10318, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 8693, 2781, 2782, 2783, 2784, 9791, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 8696, 2800, 2801, 2802, 2803, 2804, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 8700, 2814, 2817, 2818, 2820, 2821, 2822, 10330, 2824, 2825, 10331, 2828, 2829, 2831, 10099, 8704, 2837, 2838, 2839, 2841, 2842, 2843, 2844, 2845, 2846, 2848, 2849, 2850, 2851, 2852, 8254, 2854, 2855, 2856, 2858, 2859, 2860, 2862, 8580, 2864, 2865, 2866, 2868, 2874, 2875, 2878, 2882, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2897, 8717, 2899, 2900, 2901, 2902, 2905, 2906, 2908, 2910, 2918, 9885, 2921, 2922, 8722, 10350, 2926, 10351, 2929, 2932, 2933, 2936, 2937, 2938, 2940, 2942, 2944, 2947, 2950, 2952, 2953, 2955, 2956, 10357, 2960, 2961, 8584, 2963, 2965, 10118, 2967, 2968, 2969, 2973, 2976, 2977, 2978, 2979, 2980, 2981, 8259, 2983, 2986, 2987, 2988, 8490, 2990, 2992, 2993, 2994, 2995, 2996, 2997, 3000, 3001, 3002, 3006, 3007, 3008, 8739, 10214, 3011, 3012, 3018, 10369, 3020, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 10371, 3031, 3032, 3034, 3035, 3036, 3038, 3040, 3042, 3043, 3044, 3045, 3047, 3048, 10375, 3050, 3057, 3064, 3066, 3067, 3069, 3073, 3074, 3075, 10380, 3076, 10381, 3079, 3080, 3081, 3083, 3084, 3086, 3089, 3090, 3091, 10119, 10384, 3096, 3100, 3101, 9892, 10386, 3104, 3105, 3103, 3109, 8759, 10388, 3114, 3116, 3117, 8761, 3121, 3123, 3125, 3126, 3127, 3130, 3131, 3132, 3134, 3138, 3139, 3141, 3148, 3149, 10395, 3152, 3154, 10397, 3161, 3162, 3163, 3165, 10399, 3169, 3170, 9839, 3172, 3173, 3178, 8267, 3181, 3186, 3188, 3189, 3192, 3194, 10405, 3201, 3202, 3204, 3209, 3212, 3213, 10408, 3214, 3219, 3221, 3222, 3223, 10410, 3225, 3226, 3228, 8783, 3232, 3233, 10412, 3236, 3237, 8785, 3242, 3243, 3247, 3250, 3251, 3255, 9774, 3257, 3260, 8789, 8596, 3265, 3268, 3269, 3271, 3273, 3274, 3275, 9899, 3278, 3279, 3281, 3282, 3283, 3285, 3286, 3287, 3289, 3290, 3302, 3303, 3304, 3306, 8799, 3311, 3313, 3317, 3333, 3335, 8599, 3341, 3346, 3347, 3351, 3352, 3353, 3355, 8808, 3357, 3360, 3361, 8809, 3365, 3366, 8810, 3368, 3369, 8811, 3372, 9903, 3380, 3381, 3382, 10229, 3384, 3385, 3386, 3387, 3389, 3390, 3394, 3396, 3398, 3399, 9904, 3401, 8817, 3402, 3404, 3405, 8276, 8602, 3415, 3416, 3419, 3420, 3425, 9796, 3427, 2309, 8277, 3432, 3434, 3435, 3437, 3438, 3443, 3448, 3450, 3451, 3453, 8278, 3455, 3457, 10232, 3464, 3465, 3466, 3467, 8830, 3470, 3471, 9907, 3476, 3477, 3481, 3484, 3485, 3487, 8834, 3495, 3500, 3503, 3504, 3505, 10234, 3512, 3513, 3516, 3520, 3521, 3522, 9909, 3526, 701, 8281, 3532, 3535, 3538, 3544, 3547, 8846, 3550, 9797, 9910, 8282, 3555, 3556, 3558, 3559, 3562, 8850, 3568, 3576, 8852, 8854, 3591, 3593, 3594, 3596, 3598, 3599, 3607, 3609, 3612, 3615, 3619, 8861, 3623, 3628, 3633, 3636, 3637, 3640, 3641, 8865, 3647, 3648, 3649, 3656, 3657, 3662, 3666, 3667, 3669, 3672, 3674, 3677, 3686, 3687, 3688, 3689, 3693, 3694, 3695, 8875, 3698, 3700, 3703, 3705, 3707, 3708, 3709, 10242, 3718, 3719, 3721, 3722, 3723, 3724, 8881, 3726, 3728, 3731, 3732, 8496, 3741, 3743, 3746, 3749, 3752, 3755, 3756, 3759, 3763, 3764, 3771, 9919, 3780, 3781, 3782, 8893, 3784, 3785, 3787, 3789, 3800, 9920, 3806, 3811, 3812, 3815, 3820, 3822, 3823, 10190, 3827, 3829, 3832, 8293, 3837, 8904, 3840, 10247, 3844, 3846, 3847, 3848, 3851, 3854, 3855, 9922, 8908, 3864, 3865, 8909, 10248, 8910, 3870, 8911, 3877, 3878, 3883, 8913, 3885, 3888, 3890, 3895, 3897, 8916, 3902, 3903, 3907, 3908, 3915, 3918, 3920, 3921, 3923, 9800, 3926, 8922, 3931, 3934, 8297, 3945, 3948, 3955, 3958, 3959, 3960, 3973, 3979, 3980, 3981, 3987, 3988, 3997, 4002, 4003, 8937, 4006, 4007, 4017, 4020, 8940, 4026, 4027, 9929, 8301, 8943, 4038, 4039, 4040, 4041, 4044, 4045, 4050, 8946, 4053, 4057, 4058, 4059, 4060, 4061, 4062, 4065, 8949, 4069, 8950, 4071, 4073, 4074, 4076, 4081, 4084, 8303, 4087, 4091, 4093, 4097, 4107, 4109, 8304, 8499, 8958, 4111, 4115, 8959, 4122, 9933, 8962, 4132, 4133, 4134, 4138, 4140, 4145, 4146, 4150, 8306, 4160, 4168, 4170, 4171, 4174, 4175, 4178, 4179, 4180, 4181, 4182, 8973, 4189, 4192, 8975, 4201, 4205, 4206, 4207, 9936, 4208, 4213, 4215, 10128, 4218, 8980, 4229, 8309, 4240, 4241, 4242, 8984, 4244, 4247, 8987, 4261, 4273, 4274, 4280, 4282, 4287, 8993, 4290, 4293, 4294, 4296, 4299, 4306, 4307, 4308, 4310, 4316, 4318, 4322, 9000, 4324, 4325, 9002, 4340, 4341, 9004, 4352, 10161, 9007, 4358, 4359, 4360, 4363, 4368, 4372, 4373, 4379, 4381, 4383, 4384, 4386, 9013, 4391, 9014, 4395, 4399, 4400, 4405, 4413, 2506, 4431, 9022, 8317, 4437, 4440, 4441, 2511, 4444, 4447, 4450, 4451, 4457, 8318, 4461, 4463, 

In [42]:
print(custom_detect_outlier(dataframe= df, col= 'Other_Sales', lower_bound_percentage= 0.1, upper_bound_percentage= 0.9))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 8890, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 9103, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 8348, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 9434, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 8415, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 8421, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 8424, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 9669, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 8442, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 8529, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 8547, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 8552, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 10393, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2074, 2252, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 8592, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 8558, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 10231, 2331, 2332, 2333, 8559, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 10235, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 8609, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 8617, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 9865, 2423, 2424, 2425, 2427, 10191, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2428, 2438, 2439, 2440, 2441, 2442, 2443, 2437, 2445, 2446, 2447, 2448, 2449, 8238, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 8564, 2464, 2465, 2466, 10259, 2468, 2463, 2470, 2471, 2472, 2473, 2475, 2476, 8633, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 8634, 2477, 2487, 2488, 2486, 2490, 2491, 2492, 2493, 2494, 2495, 10265, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2505, 8639, 2507, 2508, 2509, 2510, 10268, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 8642, 2524, 2525, 2526, 2527, 2523, 2529, 2530, 2531, 2532, 2533, 2534, 8644, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 8242, 2557, 2559, 2561, 8650, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 9871, 2575, 2576, 10281, 2578, 2579, 2580, 2577, 2582, 2583, 2584, 2585, 2586, 2587, 8467, 2590, 2591, 2592, 2593, 2595, 2596, 2597, 8657, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 8658, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2607, 2617, 2618, 2619, 2620, 8662, 2622, 2623, 2624, 8245, 2626, 2627, 2628, 2629, 2630, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 8667, 2648, 2649, 2650, 2651, 2652, 8668, 2654, 2655, 2656, 2657, 10297, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2674, 2676, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 10201, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 8676, 2696, 2695, 2699, 2700, 2701, 2702, 8248, 2704, 8678, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2716, 2717, 2718, 2719, 10309, 2722, 2723, 2724, 2725, 10311, 2727, 2728, 10203, 2730, 2731, 8575, 2732, 2734, 2735, 2733, 2737, 2740, 2741, 2742, 2744, 2745, 2746, 2747, 2748, 1715, 2750, 2751, 10316, 2753, 2754, 2755, 2756, 8689, 2758, 2760, 10318, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 8693, 2781, 2782, 2783, 2784, 9791, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 8696, 2800, 2801, 2802, 2803, 2804, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 8700, 2814, 2817, 2818, 2820, 2821, 2822, 10330, 2824, 2825, 10331, 2828, 2829, 2831, 10099, 8704, 2837, 2838, 2839, 2841, 2842, 2843, 2844, 2845, 2846, 2848, 2849, 2850, 2851, 2852, 8254, 2854, 2855, 2856, 2858, 2859, 2860, 2862, 8580, 2864, 2865, 2866, 2868, 2874, 2875, 2878, 2882, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2897, 8717, 2899, 2900, 2901, 2902, 2905, 2906, 2908, 2910, 2918, 9885, 2921, 2922, 8722, 10350, 2926, 10351, 2929, 2932, 2933, 2936, 2937, 2938, 2940, 2942, 2944, 2947, 2950, 2952, 2953, 2955, 2956, 10357, 2960, 2961, 8584, 2963, 2965, 10118, 2967, 2968, 2969, 2973, 2976, 2977, 2978, 2979, 2980, 2981, 8259, 2983, 2986, 2987, 2988, 8490, 2990, 2992, 2993, 2994, 2995, 2996, 2997, 3000, 3001, 3002, 3006, 3007, 3008, 8739, 10214, 3011, 3012, 3018, 10369, 3020, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 10371, 3031, 3032, 3034, 3035, 3036, 3038, 3040, 3042, 3043, 3044, 3045, 3047, 3048, 10375, 3050, 3057, 3064, 3066, 3067, 3069, 3073, 3074, 3075, 10380, 3076, 10381, 3079, 3080, 3081, 3083, 3084, 3086, 3089, 3090, 3091, 10119, 10384, 3096, 3100, 3101, 9892, 10386, 3104, 3105, 3103, 3109, 8759, 10388, 3114, 3116, 3117, 8761, 3121, 3123, 3125, 3126, 3127, 3130, 3131, 3132, 3134, 3138, 3139, 3141, 3148, 3149, 10395, 3152, 3154, 10397, 3161, 3162, 3163, 3165, 10399, 3169, 3170, 9839, 3172, 3173, 3178, 8267, 3181, 3186, 3188, 3189, 3192, 3194, 10405, 3201, 3202, 3204, 3209, 3212, 3213, 10408, 3214, 3219, 3221, 3222, 3223, 10410, 3225, 3226, 3228, 8783, 3232, 3233, 10412, 3236, 3237, 8785, 3242, 3243, 3247, 3250, 3251, 3255, 9774, 3257, 3260, 8789, 8596, 3265, 3268, 3269, 3271, 3273, 3274, 3275, 9899, 3278, 3279, 3281, 3282, 3283, 3285, 3286, 3287, 3289, 3290, 3302, 3303, 3304, 3306, 8799, 3311, 3313, 3317, 3333, 3335, 8599, 3341, 3346, 3347, 3351, 3352, 3353, 3355, 8808, 3357, 3360, 3361, 8809, 3365, 3366, 8810, 3368, 3369, 8811, 3372, 9903, 3380, 3381, 3382, 10229, 3384, 3385, 3386, 3387, 3389, 3390, 3394, 3396, 3398, 3399, 9904, 3401, 8817, 3402, 3404, 3405, 8276, 8602, 3415, 3416, 3419, 3420, 3425, 9796, 3427, 2309, 8277, 3432, 3434, 3435, 3437, 3438, 3443, 3448, 3450, 3451, 3453, 8278, 3455, 3457, 10232, 3464, 3465, 3466, 3467, 8830, 3470, 3471, 9907, 3476, 3477, 3481, 3484, 3485, 3487, 8834, 3495, 3500, 3503, 3504, 3505, 10234, 3512, 3513, 3516, 3520, 3521, 3522, 9909, 3526, 701, 8281, 3532, 3535, 3538, 3544, 3547, 8846, 3550, 9797, 9910, 8282, 3555, 3556, 3558, 3559, 3562, 8850, 3568, 3576, 8852, 8854, 3591, 3593, 3594, 3596, 3598, 3599, 3607, 3609, 3612, 3615, 3619, 8861, 3623, 3628, 3633, 3636, 3637, 3640, 3641, 8865, 3647, 3648, 3649, 3656, 3657, 3662, 3666, 3667, 3669, 3672, 3674, 3677, 3686, 3687, 3688, 3689, 3693, 3694, 3695, 8875, 3698, 3700, 3703, 3705, 3707, 3708, 3709, 10242, 3718, 3719, 3721, 3722, 3723, 3724, 8881, 3726, 3728, 3731, 3732, 8496, 3741, 3743, 3746, 3749, 3752, 3755, 3756, 3759, 3763, 3764, 3771, 9919, 3780, 3781, 3782, 8893, 3784, 3785, 3787, 3789, 3800, 9920, 3806, 3811, 3812, 3815, 3820, 3822, 3823, 10190, 3827, 3829, 3832, 8293, 3837, 8904, 3840, 10247, 3844, 3846, 3847, 3848, 3851, 3854, 3855, 9922, 8908, 3864, 3865, 8909, 10248, 8910, 3870, 8911, 3877, 3878, 3883, 8913, 3885, 3888, 3890, 3895, 3897, 8916, 3902, 3903, 3907, 3908, 3915, 3918, 3920, 3921, 3923, 9800, 3926, 8922, 3931, 3934, 8297, 3945, 3948, 3955, 3958, 3959, 3960, 3973, 3979, 3980, 3981, 3987, 3988, 3997, 4002, 4003, 8937, 4006, 4007, 4017, 4020, 8940, 4026, 4027, 9929, 8301, 8943, 4038, 4039, 4040, 4041, 4044, 4045, 4050, 8946, 4053, 4057, 4058, 4059, 4060, 4061, 4062, 4065, 8949, 4069, 8950, 4071, 4073, 4074, 4076, 4081, 4084, 8303, 4087, 4091, 4093, 4097, 4107, 4109, 8304, 8499, 8958, 4111, 4115, 8959, 4122, 9933, 8962, 4132, 4133, 4134, 4138, 4140, 4145, 4146, 4150, 8306, 4160, 4168, 4170, 4171, 4174, 4175, 4178, 4179, 4180, 4181, 4182, 8973, 4189, 4192, 8975, 4201, 4205, 4206, 4207, 9936, 4208, 4213, 4215, 10128, 4218, 8980, 4229, 8309, 4240, 4241, 4242, 8984, 4244, 4247, 8987, 4261, 4273, 4274, 4280, 4282, 4287, 8993, 4290, 4293, 4294, 4296, 4299, 4306, 4307, 4308, 4310, 4316, 4318, 4322, 9000, 4324, 4325, 9002, 4340, 4341, 9004, 4352, 10161, 9007, 4358, 4359, 4360, 4363, 4368, 4372, 4373, 4379, 4381, 4383, 4384, 4386, 9013, 4391, 9014, 4395, 4399, 4400, 4405, 4413, 2506, 4431, 9022, 8317, 4437, 4440, 4441, 2511, 4444, 4447, 4450, 4451, 4457, 8318, 4461, 4463, 

# Data Analysis & Insights

### Top 10 Games by Global Sales

In [138]:
Top_10_Games= df.nlargest(10, 'Global_Sales')[['Name','Global_Sales']]
print(Top_10_Games)

                        Name  Global_Sales
0                 Wii Sports         82.74
1          Super Mario Bros.         40.24
2             Mario Kart Wii         35.82
3          Wii Sports Resort         33.00
4   Pokemon Red/Pokemon Blue         31.37
5                     Tetris         30.26
6      New Super Mario Bros.         30.01
7                   Wii Play         29.02
8  New Super Mario Bros. Wii         28.62
9                  Duck Hunt         28.31

### Total Global Sales by Genre

In [61]:
genre_sales = df.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False)
print(genre_sales)

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Misc             809.96
Racing           732.04
Fighting         448.91
Simulation       392.20
Puzzle           244.95
Adventure        239.04
Strategy         175.12
Name: Global_Sales, dtype: float64

In [60]:
px.bar(genre_sales.reset_index(), x='Genre', y='Global_Sales', title='Total Global Sales by Genre', text_auto= True)

In [136]:
px.pie(data_frame=df,names='Genre',title='Genres by Total Global Sales',hole=0.35)

### Total Global Sales by Platform

In [76]:
platform_sales = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False)
print(platform_sales.head(10))

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Wii      926.71
DS       822.49
PS       730.66
GBA      318.50
PSP      296.28
PS4      278.10
PC       258.82
Name: Global_Sales, dtype: float64

In [79]:
px.bar(platform_sales.reset_index(), x='Platform', y='Global_Sales', title='Total Global Sales by Platform', text_auto= True)

### Sales Trends Over Time

In [81]:
year_sales = df.groupby('Year')['Global_Sales'].sum().reset_index()

In [85]:
px.line(year_sales, x='Year', y='Global_Sales', title='Global Sales Trend by Year', markers= True)

In [150]:
NA_year_sales = df.groupby('Year')['NA_Sales'].sum().reset_index()

In [152]:
px.line(NA_year_sales, x='Year', y='NA_Sales', title='North America Sales Trend by Year', markers= True)

In [ ]:
EU_year_sales = df.groupby('Year')['EU_Sales'].sum().reset_index()

In [154]:
px.line(EU_year_sales, x='Year', y='EU_Sales', title='Europe Sales Trend by Year', markers= True)

In [155]:
JP_year_sales = df.groupby('Year')['JP_Sales'].sum().reset_index()

In [157]:
px.line(JP_year_sales, x='Year', y='JP_Sales', title='Japan Sales Trend by Year', markers= True)

In [160]:
Other_year_sales = df.groupby('Year')['Other_Sales'].sum().reset_index()

In [161]:
px.line(Other_year_sales, x='Year', y='Other_Sales', title='Other Sales Trend by Year', markers= True)

In [118]:
Top_10_years_by_sales=year_sales.sort_values('Global_Sales', ascending=False).head(10)
print(Top_10_years_by_sales)

    Year  Global_Sales
27  2007        711.21
28  2008        678.90
29  2009        667.30
30  2010        600.45
26  2006        521.04
31  2011        515.99
25  2005        459.94
24  2004        419.31
22  2002        395.52
33  2013        368.11

### Regional Analysis

In [139]:
region_sales = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
print(region_sales)

NA_Sales       4392.95
EU_Sales       2434.13
JP_Sales       1291.02
Other_Sales     797.75
dtype: float64

In [89]:
market_share = region_sales / region_sales.sum() * 100
print(market_share)

NA_Sales       49.271242
EU_Sales       27.301155
JP_Sales       14.480055
Other_Sales     8.947548
dtype: float64

### Publisher Performance

In [94]:
publisher_sales = df.groupby('Publisher')['Global_Sales'].sum().sort_values(ascending=False)
print(publisher_sales.head(15))

Publisher
Nintendo                                  1786.56
Electronic Arts                           1110.32
Activision                                 727.46
Sony Computer Entertainment                607.50
Ubisoft                                    474.72
Take-Two Interactive                       399.54
THQ                                        340.77
Konami Digital Entertainment               283.64
Sega                                       272.99
Namco Bandai Games                         254.09
Microsoft Game Studios                     245.79
Capcom                                     200.89
Atari                                      157.22
Warner Bros. Interactive Entertainment     153.89
Square Enix                                145.18
Name: Global_Sales, dtype: float64

In [95]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

### Sales Correlation

In [110]:
Sales_cols= ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']

In [100]:
Sales_corr = df[Sales_cols].corr()

In [102]:
px.imshow(Sales_corr, text_auto=True, title="Sales Correlation")

### Group by families

In [128]:
def platform_family(p):
    if p in ['PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV']:
        return 'PlayStation'
    elif p in ['X360', 'XB', 'XOne']:
        return 'Xbox'
    elif p in ['Wii', 'WiiU', 'GC', 'DS', '3DS', 'NES', 'SNES', 'N64', 'GB', 'GBA']:
        return 'Nintendo'
    elif p in ['PC']:
        return 'PC'
    else:
        return 'Other'

df['Platform_Family'] = df['Platform'].apply(platform_family)

In [129]:
family_sales = df.groupby('Platform_Family')['Global_Sales'].sum().reset_index()

In [130]:
px.bar(family_sales, x='Platform_Family', y='Global_Sales', title='Total Sales by Platform Family', text_auto= True).update_xaxes(categoryorder = 'max descending')

In [148]:
px.pie(data_frame=df,names='Platform_Family',title='Genres by Total Global Sales',hole=0.35)